sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t rorygraves/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rorygraves/udemy-docker-react npm run test
  
